language: node_js
node_js:
- "12"
script: npm run build
#env:
  #global:
  #- ENCRYPTION_LABEL: "0f3a5a820540"
  #- COMMIT_AUTHOR_EMAIL: "travis-bot@game-jam-do.de"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
